<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class PixelGreenThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("PixelGreen");
        $this->setVersion("0.1");
        $this->setAuthor("ZenMagick");
        $this->setDescription("PixelGreen theme; generated by ZMThemeBuilder.");
    }
    
}

?>
