<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class PixelGreenThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("Pixel Green");
        $this->setVersion("${theme.version}");
        $this->setAuthor("ZenMagick");
        $this->setDescription("Pixel Green; based on work by ealigam as found at styleshout.com.");
    }
    
}

?>
