page:
  #catalog
  categories:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  product:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  product_types:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  products_price_manager:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  options_name_manager:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  options_values_manager:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  attributes_controller:
    template: views/zc_admin.php
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  downloads_manager:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  option_name:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  option_values:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  manufacturers:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  reviews:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  specials:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  featured:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  salemaker:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  products_expected:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # modules
  modules:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # location/taxes
  countries:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  zones:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  geo_zones:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  tax_classes:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  tax_rates:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # localization
  currencies:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  languages:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  orders_status:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # customers
  customers:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # @todo overrides the zm order controller make this configurable
    template: views/zc_admin.php
  orders:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  group_pricing:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  paypal:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # reports
  stats_products_viewed:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  stats_products_purchased:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  stats_customers:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  stats_products_lowstock:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  stats_customers_referrals:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # tools
  layout_controller:
    template: views/zc_admin.php
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  banner_manager:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  mail:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  newsletters:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  whos_online:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  store_manager:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  developers_tool_kit:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  # coupons/gift certificates
  coupon_admin:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  gv_queue:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  gv_mail:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php
  gv_sent:
    controller: zenmagick\apps\store\bundles\ZenCartBundle\controller\AdminController
    template: views/zc_admin.php

