<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class BrightsideoflifeThemeInfo extends ZMThemeInfo {

    /**
     * Create new instance.
     */
    function __construct() {
        parent::__construct();

        $this->setName("Bright Side of Life");
        $this->setVersion('${theme.version}');
        $this->setAuthor("ZenMagick");
        $this->setDescription("Bright Side of Life; A ZenMagick theme based on work by ealigam (as found at opendesigns.org).");
    }
    
}

?>
