<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class BrightsideoflifeThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("brightsideoflife");
        $this->setVersion("${theme.version}");
        $this->setAuthor("ZenMagick");
        $this->setDescription("brightsideoflife theme; generated by ZMThemeBuilder.");
    }
    
}

?>
