#
# default settings
#
# $Id$
#
#
zenmagick.mvc.templates.ext: .php
zenmagick.mvc.seo.type: realpath

zenmagick.core.logging.enabled: true
zenmagick.core.logging.level: ALL

zenmagick.core.database.provider: ZMPdoDatabase
zenmagick.core.database.mappings.file: config/db_mappings.txt

zenmagick.mvc.seo.type: default
#zenmagick.mvc.view.default: ZMSavantView#viewDir=
zenmagick.mvc.view.default: ZMSavantView
zenmagick.mvc.request.seoRewriter: DefaultSeoRewriter
zenmagick.mvc.view.defaultLayout: default_layout
zenmagick.mvc.html.xhtml: false
zenmagick.mvc.html.charset: utf-8

zenmagick.mvc.sacs.handler: AdminUserSacsHandler

#zenmagick.mvc.request.index: zm.php
zenmagick.mvc.request.index: index.php
zenmagick.mvc.session.userFactory: AdminUserFactory

# show login again if no session possible
zenmagick.mvc.request.invalidSession: login

zenmagick.mvc.toolbox.tools: net:ToolboxNet,html:ToolboxHtml,form:ToolboxForm,macro:ToolboxMacro,locale:ToolboxLocale,utils:ToolboxUtils,admin:ToolboxAdmin,admin2:ToolboxAdmin2
