#
# default settings
#
# $Id$
#
#
zenmagick.mvc.templates.ext: .tpl
zenmagick.mvc.seo.type: realpath

zenmagick.core.database.mappings.file: config/db_mappings.txt

zenmagick.mvc.seo.type: default
zenmagick.mvc.view.default: ZMSavantView
zenmagick.mvc.request.seoRewriter: DefaultSeoRewriter
zenmagick.mvc.view.defaultLayout: null

zenmagick.mvc.toolbox.tools: net:ToolboxNet,html:ToolboxHtml,form:ToolboxForm,macro:ToolboxMacro,locale:ToolboxLocale,utils:ToolboxUtils,admin:ToolboxAdmin
