#
# default settings
#

zenmagick.mvc.templates.ext: .php

zenmagick.core.locales.locale: en_NZ

zenmagick.core.logging.enabled: true
zenmagick.core.logging.level: ALL

zenmagick.core.database.provider: ZMPdoDatabase
zenmagick.core.database.mappings.file: config/db_mappings.txt

zenmagick.mvc.view.default: ZMSavantView
zenmagick.mvc.view.defaultLayout: default_layout

zenmagick.mvc.request.seoRewriter: DefaultSeoRewriter
zenmagick.mvc.seo.type: realpath

zenmagick.mvc.html.xhtml: false
zenmagick.mvc.html.charset: utf-8

zenmagick.mvc.sacs.handler: UserRoleSacsHandler

## the main request handler (ie. the single point of entry in admin/web)
zenmagick.mvc.request.index: index.php
## show login again if no session possible; this is a requestId
zenmagick.mvc.request.invalidSession: login

zenmagick.mvc.rpc.format: JSON

zenmagick.mvc.session.userFactory: AdminUserFactory

## toolbox tools
zenmagick.mvc.toolbox.tools: net:ToolboxNet,html:ToolboxHtml,form:ToolboxForm,macro:ToolboxMacro,locale:ToolboxLocale,utils:ToolboxUtils,admin:ToolboxAdmin,admin2:ToolboxAdmin2

## all available dashboard widgets
apps.store.dashboad.widgets: ZMOrderStatsDashboardWidget,ZMLatestOrdersDashboardWidget,ZMLatestAccountsDashboardWidget,ZMRecentSearchesDashboardWidget,ZMUpdateCheckerDashboardWidget

## this is JSON
apps.store.dashboad.default: '{"layout":"col2l","widgets":[["ZMOrderStatsDashboardWidget","ZMLatestAccountsDashboardWidget"],["ZMLatestOrdersDashboardWidget"]]}'
apps.store.catalog.controller: CatalogDefaultTabController
