#
# ZenMagick admin default SACS mappings
#
# $Id$
#
#

## default for not explicitely mapped requests
default:
  secure: true
  ## require admin role
  roles: 
    - admin

## explicit mappings
mappings:
  ###########################################
  ## no permission at all
  ##
  login: 
    secure: true
  logoff: 
    secure: true
  reset_password: 
    secure: true

  ###########################################
  ## allow for all users (empty roles list)
  ##
  ajax_plugin_admin: 
    secure: true
    roles:
  ajax_dashboard: 
    secure: true
    roles:
  index: 
    secure: true
    roles:

  ###########################################
  ## explicit permissions (either roles or users or both)
  ##
  orders: 
    roles: 
      - admin
      - demo
    secure: true
  order: 
    roles: 
      - admin
      - demo
    secure: true
  accounts: 
    roles: 
      - admin
      - demo
    secure: true
  account: 
    roles: 
      - admin
      - demo
    secure: true
  installation: 
    roles: 
      - admin
    secure: true
  plugins: 
    roles: 
      - admin
      - demo
    secure: true
  catalog_manager: 
    roles: 
      - admin
      - demo
    secure: true
  cache_admin: 
    roles: 
      - admin
      - demo
    secure: true
  l10n: 
    roles: 
      - admin
      - demo
    secure: true
  theme_builder: 
    roles: 
      - admin
      - demo
    secure: true
  static_page_editor: 
    roles: 
      - admin
      - demo
    secure: true
  ezpages: 
    roles: 
      - admin
      - demo
    secure: true
  admin_users: 
    roles: 
      - admin
      - demo
    secure: true
  edit_admin_user: 
    roles: 
      - admin
    secure: true
  configuration: 
    roles: 
      - admin
      - demo
    secure: false
  legacy-config: 
    roles: 
      - admin
      - demo
    secure: false
  tools: 
    roles: 
      - admin
      - demo
    secure: false
  about: 
    roles: 
      - admin
      - demo
    secure: false
