#
# ZenMagick admin default SACS mappings
#
# $Id$
#
#

## default for not explicitely mapped requests
default:
  secure: true
  roles: 
    - admin

## explicit mappings
mappings:
  ajax_plugin_admin: 
    secure: true
    roles:
  login: 
    secure: true
    roles:
  logoff: 
    secure: true
    roles:
  reset_password: 
    secure: true
    roles:
  index: 
    roles: 
      - admin
      - demo
    secure: true
  orders: 
    roles: 
      - admin
      - demo
    secure: true
  order: 
    roles: 
      - admin
      - demo
    secure: true
  accounts: 
    roles: 
      - admin
      - demo
    secure: true
  account: 
    roles: 
      - admin
      - demo
    secure: true
  installation: 
    roles: 
      - admin
    secure: true
  plugins: 
    roles: 
      - admin
    secure: true
  catalog_manager: 
    roles: 
      - admin
      - demo
    secure: true
  cache_admin: 
    roles: 
      - admin
    secure: true
  l110n: 
    roles: 
      - admin
    secure: true
  theme_builder: 
    roles: 
      - admin
    secure: true
  static_page_editor: 
    roles: 
      - admin
    secure: true
  ezpages: 
    roles: 
      - admin
      - demo
    secure: true
  admin_users: 
    roles: 
      - admin
      - demo
    secure: true
  about: 
    roles: 
      - admin
      - demo
    secure: false
