null:
  error:
    template: error
    layout: 
  success-demo:
    view: RedirectView
    
login:
  success:
    view: RedirectView
    template: index
  logged-in:
    view: RedirectView
    template: index
logoff:
  success:
    view: RedirectView
    template: login
reset_password:
  success:
    view: RedirectView
    template: login
update_user:
  formId: updateUser
  form: AdminUserForm
  success:
    view: RedirectView
    template: index
edit_admin_user:
  formId: adminUser
  form: AdminUserForm
  success:
    view: RedirectView
    template: admin_users
plugins:
  success-install:
    view: RedirectView
    template: plugins
  success-uninstall:
    view: RedirectView
    template: plugins
  success-upgrade:
    view: RedirectView
    template: plugins
  plugin-conf:
    layout: 
    template: plugin_conf
manage_roles:
  layout:
legacy-config:
  success:
    view: RedirectView
    template: legacy-config
