login:
  success:
    view: RedirectView
    template: index
  logged-in:
    view: RedirectView
    template: index
logoff:
  success:
    view: RedirectView
    template: login
plugins:
  success-install:
    view: RedirectView
    template: plugins
  success-uninstall:
    view: RedirectView
    template: plugins
  success-upgrade:
    view: RedirectView
    template: plugins
