<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class PrecisionReloadedThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("PrecisionReloaded");
        $this->setVersion("0.1");
        $this->setAuthor("ZenMagick");
        $this->setDescription("PrecisionReloaded theme; generated by ZMThemeBuilder.");
    }
    
}

?>
