<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class PrecisionReloadedThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("Precision Reloaded");
        $this->setVersion("${theme.version}");
        $this->setAuthor("David");
        $this->setDescription("Precision Reloaded  - a liquid three column theme based on the ZenMagick Precision theme.");
    }
    
}

?>
