imports:
    ## app config
    - { resource: config.yaml }
    ## shared config
    - { resource: ../../../config/store-config.yaml }
    ## shared dev config
    - { resource: ../../../config/store-config_dev.yaml }
    ## custom local config
    - { resource: local-config.yaml, mode: append }
    ## custom local dev config
    - { resource: local-config_dev.yaml, mode: append }

zenmagick:
  base:
    logging:
      level: ALL
      enabled: true
      handleErrors: true
      handlers:
        - zenmagick\base\logging\handler\DefaultLoggingHandler
        - zenmagick\base\logging\handler\EchoLoggingHandler#logLevel=WARN
