# the route key will be set as requestId
login:
  pattern: /login
  ## new routing using the traditional, single-method ZenMagick controller
  defaults: { _controller: ZMLoginController:process }
  requirements:
    _scheme: https

