#
# ZenMagick admin SACS mappings
#
#

## default for not explicitely mapped requests
default:
  secure: true
  ## require admin role
  roles:
    - admin

## explicit mappings
mappings:
  ###########################################
  ## allowed for all (wildcard users)
  ##
  login:
    users:
      - '*'
  logoff:
    users:
      - '*'
  reset_password:
    users:
      - '*'

  ###########################################
  ## allow for all valid users (wildcard role)
  ##
  ajax_plugin_admin:
    roles:
      - '*'
  ajax_dashboard:
    roles:
      - '*'
  index:
    roles:
      - '*'
