#
# ZenMagick admin default SACS mappings
#
#

## default for not explicitely mapped requests
default:
  secure: true
  ## require admin role
  roles: 
    - admin

## explicit mappings
mappings:
  ###########################################
  ## no permission at all
  ##
  login: 
    secure: true
  logoff: 
    secure: true
  reset_password: 
    secure: true

  ###########################################
  ## allow for all valid users (empty roles list)
  ##
  ajax_plugin_admin: 
    secure: true
    roles:
  ajax_dashboard: 
    secure: true
    roles:
  index: 
    secure: true
    roles:
