<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class KeepItSimpleThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName('Keep It Simple');
        $this->setVersion('${theme.version}');
        $this->setAuthor('ZenMagick');
        $this->setDescription('Keep It Simple; based on the KeepItSimple template at styleshout.com.');
    }
    
}

?>
