<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class KeepItSimpleThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("KeepItSimple");
        $this->setVersion("${theme.version}");
        $this->setAuthor("ZenMagick");
        $this->setDescription("KeepItSimple theme; generated by ZMThemeBuilder.");
    }
    
}

?>
