'zenmagick.core.database.model.keyName'
'zenmagick.core.database.tablePrefix'
'zenmagick.core.database.isCacheDbMappings'
'zenmagick.core.database.mappings'
'zenmagick.core.database.isAutoMapping'
'zenmagick.core.database.sql.[table].customFields'
'zenmagick.core.authentication.minPasswordLength'
'zenmagick.core.fs.permissions.folder'
