zenmagick_admin:
    resource: "@AdminBundle/Resources/config/routing.xml"
    prefix:   /admin
zenmagick_storefront:
    resource: "@StorefrontBundle/Resources/config/routing.xml"
    prefix: /
zencart_admin:
    resource: "@ZenCartBundle/Resources/config/routing/admin.xml"
    prefix: /admin/zencart
