zenmagick_admin:
    resource: "@AdminBundle/Resources/config/routing.xml"
    prefix:   /admin
zenmagick_storefront:
    resource: "@StorefrontBundle/Resources/config/routing.xml"
    prefix: /
zencart_admin:
    resource: "@ZenCartBundle/Resources/config/routing/admin.xml"
    prefix: /admin/zencart
zenmagick_plugins:
# this route is last since plugins should be able to override all routes.
    resource: .
    type: context
