#
# Form validation rules
#
# $Id$
#

mynameForm:
  myname:
    RequiredRule:
      - Please enter your name.
    MinMaxRule:
      - 5
      - 0
      - Your name must contain a minimum of %2$s characters.
