<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class PrecisionThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("Precision");
        $this->setVersion("${theme.version}");
        $this->setAuthor("ZenMagick");
        $this->setDescription("Precision a theme based on the precision template found at freecsstemplates.org.");
    }
    
}

?>
