<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class PrecisionThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("precision");
        $this->setVersion("0.1");
        $this->setAuthor("ZenMagick");
        $this->setDescription("precision theme; generated by ZMThemeBuilder.");
    }
    
}

?>
