parameters:
  kernel.root_dir: %zenmagick.cacheBaseDir%/kernel
  kernel.cache_dir: %zenmagick.cacheBaseDir%
  kernel.debug: false
  kernel.bundles: %zenmagick.bundles%
  zenmagick.installationPath: '<?php echo dirname(zenmagick\base\Runtime::getInstallationPath()) ?>'
  zenmagick.cacheBaseDir: '<?php echo dirname(zenmagick\base\Runtime::getInstallationPath())."/cache/zenmagick" ?>'

services:

  pluginService:
    class: ZMPlugins
    scope: container

  validator:
    class: ZMValidator
    scope: container

  urlManager:
    class: ZMUrlManager
    scope: container

  request:
    class: ZMRequest
    scope: container

  defaultView:
    class: ZMSavantView
    scope: prototype
    calls:
      - [setConfig, [{ 'cache' => 'ZMSimpleSavantCache' }]]
      - [setFilters, ['ZMShortTagFilter']]

