#
# URL mappings
#

## global mappings
global:
  error:
    template: views/error.tpl
  index:
    template: views/index.tpl

## page mappings    
page:
  index:
    layout: default_layout.tpl
    ## name of the validation rules in validation.yaml
    formId: mynameForm
    ## form data container
    form: zenmagick\base\ZMObject
    success:
      view: redirect#requestId=index
  ## explicit mapping - not required as all defaults
  ## NOTE: there is no default layout configured, so about is a full page, not just a view
  #about:
  #  template: views/about.tpl
