#
# Form validation rules
#

mynameForm:
  myname:
    ZMRequiredRule:
      - Please enter your name.
    ZMMinMaxRule:
      - 5
      - 0
      - Your name must contain a minimum of %2$s characters.
