#
# ZenMagick admin SACS mappings
#
#

## default for not explicitely mapped requests
default:
  ## require admin role
  roles:
    - ROLE_SUPER_ADMIN

## explicit mappings
mappings:
  ###########################################
  ## allowed for all (wildcard users)
  ##
  admin_login:
    users:
      - '*'
  admin_logout:
    users:
      - '*'
  admin_reset_password:
    users:
      - '*'

  ###########################################
  ## allow for all valid users (wildcard role)
  ##
  ajax_plugin_admin:
    roles:
      - '*'
  ajax_dashboard:
    roles:
      - '*'
  admin_index:
    roles:
      - '*'
