<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class DefaultSmartyThemeInfo extends ZMThemeInfo {

    /**
     * Create new instance.
     */
    function __construct() {
        parent::__construct();

        $this->setName("default_smarty");
        $this->setVersion("0.1");
        $this->setAuthor("ZenMagick");
        $this->setDescription("Smarty default theme.");

        // popups use their own simple page layout
        $this->setLayout('popup_cvv_help', 'popup_layout');
        $this->setLayout('popup_search_help', 'popup_layout');
        $this->setLayout('popup_shipping_estimator', 'popup_layout');
        $this->setLayout('popup_coupon_help', 'popup_layout');
    }
    
}

?>
