<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class DefaultSmartyThemeInfo extends ZMThemeInfo {

    // c'tor PHP4
    function DefaultSmartyThemeInfo() {
        $this->__construct();
    }

    // c'tor PHP5
    function __construct() {
        parent::__construct();

        $this->setName("default_smarty");
        $this->setVersion("0.1");
        $this->setAuthor("ZenMagick");
        $this->setDescription("Smarty default theme.");
    }
    
}

?>
