<?php
/*
 * ZenMagick - Smart e-commerce
 * Copyright (C) 2006-2011 zenmagick.org
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston, MA  02110-1301, USA.
 */
?>
<?php


/**
 * Method controller.
 *
 * <p>Single controller that handles three separate page requests:</p>
 * <ul>
 *  <li><em>foo</em> - no layout, no view, content generated by the controller itself</li>
 *  <li><em>bar</em> - no layout, content generated by view template with corresponding name - bar.php (in the content/views folder)</li>
 *  <li><em>xform</em> - regular layout/view contents with get/post handled by separate function (and optional redirect view on form success)</li>
 * </ul>
 *
 * @package org.zenmagick.plugins.methodController
 * @author DerManoMann <mano@zenmagick.org>
 */
class ZMMethodController extends ZMController {

    /**
     * Create new instance.
     */
    function __construct() {
        parent::__construct();
    }

    /**
     * Destruct instance.
     */
    function __destruct() {
        parent::__destruct();
    }


    /**
     * Custom request processing <em>foo</em>.
     */
    public function foo($request) {
        echo 'foo';
        // no layout/view output
        return null;
    }

    /**
     * Custom request processing <em>bar</em>.
     */
    public function bar($request) {
        // no layout, default view
        return $this->findView();
    }

    /**
     * Custom request processing <em>xform</em>.
     */
    public function xform($request) {
        // HTTP method
        switch ($request->getMethod()) {
        case 'GET': return $this->xform_get($request);
        case 'POST': return $this->xform_post($request);
        }

        // rid independant error page (mapped under null:)
        $this->messageService->error(_zm('Invalid request method'));
        return $this->findView('error');
    }

    /**
     * Process xform GET.
     */
    protected function xform_get($request) {
        // display default
        return $this->findView();
    }

    /**
     * Process xform POST.
     */
    protected function xform_post($request) {
        $name = $request->getParameter('name');
        $viewId = null;
        if (empty($name)) {
            $this->messageService->error(_zm('Please enter a name'));
        } else {
            $this->messageService->success(_zm('The name entered was: '.$name));
            $viewId = 'success';
        }

        // display view based on processing, add name as custom view data
        // NOTE: custom data is not available if a redirect view is used
        return $this->findView($viewId, array('enteredName' => $name));
    }

}
