<?php

// theme info class generated by ZMThemeBuilder; edit at own risk
class TestThemeInfo extends ZMThemeInfo {

    // c'tor
    function __construct() {
        parent::__construct();

        $this->setName("test");
        $this->setVersion("0.1");
        $this->setAuthor("ZenMagick");
        $this->setDescription("test theme; generated by ZMThemeBuilder.");
    }
    
}

?>
