#
# default settings
#

## version
zenmagick.version: ${zenmagick.version}

## db
zenmagick.core.database.mappings.file: config/db_mappings.txt
zenmagick.core.database.mappings.cache.enabled: false
zenmagick.core.database.mappings.autoMap.enabled: true

## logging
zenmagick.core.logging.level: INFO
zenmagick.core.logging.enabled: false
zenmagick.core.logging.handleErrors: true
zenmagick.base.logging.handler: \zenmagick\base\logging\handler\DefaultLoggingHandler

## fs
zenmagick.core.fs.permissions.fix: true
zenmagick.core.fs.permissions.defaults.file: 0666
zenmagick.core.fs.permissions.defaults.folder: 0777


zenmagick.core.locales.locale: en_NZ

zenmagick.core.events.listeners: EventFixes,EmailFixes

zenmagick.mvc.request.seoRewriter: StoreDefaultSeoRewriter
zenmagick.mvc.request.idName: main_page
#zenmagick.mvc.view.default: SavantView
zenmagick.mvc.view.default: SavantView#config=cache%3DSimpleSavantCache&filters=ShortTagFilter
#zenmagick.mvc.view.default: SavantView#filters=ShortTagFilter
zenmagick.mvc.request.invalidSession: cookie_usage


zenmagick.mvc.toolbox.tools: net:ToolboxNet,html:ToolboxHtml,form:ToolboxForm,macro:ToolboxMacro,locale:ToolboxLocale,utils:ToolboxUtils,crumbtrail:ToolboxCrumbtrail,metaTags:ToolboxMetaTags

zenmagick.mvc.html.dir: ltr
zenmagick.mvc.html.xhtml: true
zenmagick.mvc.html.charset: utf-8

