imports:
    - { resource: config.yaml }
    - { resource: ../../../config/store-config.yaml }
    - { resource: local-config.yaml, mode: append }
    - { resource: local-config_production.yaml, mode: append }
