#
# storefront default settings
#

## general settings
zenmagick:
  version: ${zenmagick.version}

  ## core
  core:
    ## db
    database:
      provider: ZMPdoDatabase
      mappings:
        file: config/db_mappings.txt
        cache:
          enabled: false
        autoMap:
          enabled: true

    ## locales
    locales:
      locale: en_NZ
      provider: ZMYamlLocale

    ## security
    security:
      defaultAuthenticationProvider: ZMZenCartAuthentication

    ## fs
    fs:
      permissions:
        fix: true
        defaults:
          file: 0666
          folder: 0777

  ## base
  base:
    ## events
    events:
      listeners:
        ## TODO: these should be swapped
        - zenmagick\apps\store\StoreEventListener
        - zenmagick\http\BootstrapListener
        - ZMEventFixes
        - ZMEmailFixes
    ## logging
    logging:
      level: INFO
      enabled: false
      handleErrors: true
      handlers:
        - zenmagick\base\logging\handler\DefaultLoggingHandler
    ## plugins
    plugins:
      context: 1


  ## mvc
  mvc:
    ## request
    request:
      missingPage: error

    ## html
    html:
      xhtml: true
      charset: utf-8
      tokenSecuredForms: login
 
    ## view
    view:
      #default: SavantView
      default: 'SavantView#config=cache%3DZMSimpleSavantCache&filters=ShortTagFilter'
      defaultLayout: default_layout

    ## toolbox tools
    toolbox:
      tools:
        - net:ZMToolboxNet
        - html:ZMToolboxHtml
        - form:ZMToolboxForm
        - macro:ZMToolboxMacro
        - locale:ZMToolboxLocale
        - utils:ZMToolboxUtils
        - crumbtrail:ZMToolboxCrumbtrail
        - metaTags:ZMToolboxMetaTags

    ## resultlist
    resultlist:
      defaultPagination: 10

  http:
    ## request
    request:
      idName: main_page
      invalidSession: cookie_usage
      login: login
      urlRewriter: 
        - StoreDefaultUrlRewriter
    ## sacs
    sacs:
      handler:
        - ZMZenCartAccountSacsHandler
  ## bundles
  bundles:
    DoctrineBundle: Symfony\Bundle\DoctrineBundle\DoctrineBundle 

apps:
  store:
    themes:
      default: default

# database configuration settings
# @todo allow symbolic names for the fully qualified classes mentioned here?
doctrine:
  dbal:
    logging: true # @todo has to be true for pageStats plugin to work
    logger_class: Doctrine\DBAL\Logging\DebugStack
    connections:
      default:
        driver: pdo_mysql
        dbname: zenmagick
        host: localhost
        port: null
        user: root
        password: null
        prefix:
        charset: utf8
        collation: null
        unix_socket: null
  orm:
    auto_generate_proxy_classes: true
    proxy_dir: proxies # @todo inside cache dir, should  we specify that here?
    proxy_namespace: zenmagick\apps\store\proxies
    metadata_cache_driver: Doctrine\Common\Cache\ArrayCache
    query_cache_driver: Doctrine\Common\Cache\ArrayCache
    result_cache_driver: Doctrine\Common\Cache\ArrayCache
    mappings:
      zenmagick:
        type: annotation
        # @todo will eventually be the namespace zenmagick\apps\store\entities
        prefix: ZM
        dir:
          - shared/model/account
          - shared/model/catalog
          - shared/model/checkout/coupons
          - shared/model/checkout
          - shared/model/forms
          - shared/model/layout
          - shared/model/locale
          - shared/model/order
          - shared/model
