#
# storefront default settings
#

## general settings
zenmagick:
  version: ${zenmagick.version}

  ## core
  core:
    ## db
    database:
      provider: ZMPdoDatabase
      mappings:
        file: config/db_mappings.txt
        cache:
          enabled: false
        autoMap:
          enabled: true

    ## locales
    locales:
      locale: en_NZ
      provider: ZMYamlLocale

    ## security
    security:
      defaultAuthenticationProvider: ZMZenCartAuthentication

    ## fs
    fs:
      permissions:
        fix: true
        defaults:
          file: 0666
          folder: 0777

  ## base
  base:
    ## events
    events:
      listeners:
        ## TODO: these should be swapped
        - zenmagick\apps\store\StoreEventListener
        - zenmagick\http\BootstrapListener
        - ZMEventFixes
        - ZMEmailFixes
    ## logging
    logging:
      level: INFO
      enabled: false
      handleErrors: true
      handlers:
        - zenmagick\base\logging\handler\DefaultLoggingHandler
    ## plugins
    plugins:
      context: 1


  ## mvc
  mvc:
    ## request
    request:
      idName: main_page
      missingPage: error
      seoRewriter: ZMStoreDefaultSeoRewriter

    ## html
    html:
      xhtml: true
      charset: utf-8
      tokenSecuredForms: login
 
    ## view
    view:
      #default: SavantView
      default: 'SavantView#config=cache%3DSimpleSavantCache&filters=ShortTagFilter'
      defaultLayout: default_layout

    ## toolbox tools
    toolbox:
      tools:
        - net:ZMToolboxNet
        - html:ZMToolboxHtml
        - form:ZMToolboxForm
        - macro:ZMToolboxMacro
        - locale:ZMToolboxLocale
        - utils:ZMToolboxUtils
        - crumbtrail:ZMToolboxCrumbtrail
        - metaTags:ZMToolboxMetaTags

    ## resultlist
    resultlist:
      defaultPagination: 10

  http:
    ## request
    request:
      invalidSession: cookie_usage
      login: login
    ## sacs
    sacs:
      handler:
        - ZMZenCartAccountSacsHandler

apps:
  store:
    themes:
      default: default
