services:
  ZMRequest:
    class: Request
    scope: prototype
  ZMPlugins:
    class: Plugins
    scope: container
  ZMSession:
    class: Session
    scope: container
  ZMSavantView:
    class: SavantView
    scope: container
  ZMMessages:
    class: Messages
    scope: container
  ZMForwardView:
    class: ForwardView
    scope: prototype
