imports:
    - { resource: container.yaml }
    - { resource: ../../../config/store-container.yaml }
    - { resource: local-container.yaml, mode: append }
    - { resource: local-container_dev.yaml, mode: append }
