parameters:
  # default session timeout
  storefront.session_timeout: 1440

services:
  ZMRequest:
    class: Request
    scope: prototype

  ZMPlugins:
    class: Plugins
    scope: container
  pluginService: @ZMPlugins

  ZMSession:
    class: Session
    scope: container

  StoreViewUtils:
    parent: merge:ZMViewUtils
    calls:
      - [setResourcesAsTemplates, [true]]

  ZMSavantView:
    class: SavantView
    scope: prototype
    calls:
      - [setConfig, [{ 'cache' => '3DZMSimpleSavantCache' }]]
      - [setFilters, ['ZMShortTagFilter']]
  defaultView: @ZMSavantView

  ZMMessages:
    class: Messages
    scope: container
  messageService: @ZMMessages

  ZMForwardView:
    class: ForwardView
    scope: prototype
  forwardView: @ZMForwardView

  ZMZenCartSessionHandler:
    class: ZMZenCartSessionHandler
    scope: container
    calls:
      - [setExpiryTime, [%storefront.session_timeout%]]
