##
## ZenMagick store config
##
## NOTE: This file is generated (and may be re-written) automaticlly - edit at own risk.
##
zenmagick:
  core:
    database:
      connections:
        default:
          driver: mysql
          host: localhost
          user: root
          password: root
          dbname: zmdev
          prefix: zen_
          port: null
          unix_socket: null
          initQuery: null
