##
## ZenMagick store config
##
## NOTE: This file is generated (and may be re-written) automaticlly - edit at own risk.
##
zenmagick:
  core:
    database:
      connections:
        default:
          driver: mysql
          host: '<?php echo DB_SERVER ?>'
          username: '<?php echo DB_SERVER_USERNAME ?>'
          password: '<?php echo DB_SERVER_PASSWORD ?>'
          database: '<?php echo DB_DATABASE ?>'
          prefix: '<?php echo DB_PREFIX ?>'
          port: '<?php echo (null !== ($port = @ini_get('mysql.default_port')) ? $port : null) ?>'
          socket: '<?php echo (null !== ($socket = @ini_get('mysql.default_socket')) ? $socket : null) ?>'
          initQuery: null

    email:
      transport: '<?php echo EMAIL_TRANSPORT ?>'
      smtp:
        host: '<?php EMAIL_SMTPAUTH_MAIL_SERVER ?>'
        port: '<?php EMAIL_SMTPAUTH_MAIL_SERVER_PORT ?>'
        user: '<?php EMAIL_SMTPAUTH_MAILBOX ?>'
        password: '<?php EMAIL_SMTPAUTH_PASSWORD ?>'
